env:
  browser: true
  es2020: true
  jest: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:react/jsx-runtime
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - "@typescript-eslint"
  - jest
  - react
root: true
settings:
  react:
    version: detect
