name: Run ESLint before Merging Pull Request

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: "16.20.1"

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-piuucsmaker-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-piuucsmaker-${{ hashFiles('**/package-lock.json') }}-

      - name: Lint
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: "**/*.{ts,tsx}"
          fail_on_error: true
          filter_mode: nofilter
          level: warning
          reporter: github-pr-review
