name: Run Test before Merging Pull Request

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: "16.20.1"

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Find Current Pull Request
        uses: jwalton/gh-find-current-pr@v1.3.2
        id: findPr

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.6
        with:
          prnumber: ${{ steps.findPr.outputs.number }}
